table Company
	lineageTag: 3710e1e1-3ef2-42cd-a805-2010e0dae563

	column CompanyId
		dataType: int64
		formatString: 0
		lineageTag: 0dd97b9b-d4c5-4021-8778-115d7bcfa186
		summarizeBy: none
		sourceColumn: CompanyId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column _increment_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: a00c4e5d-78d2-45d8-9749-798811c49b6a
		summarizeBy: none
		sourceColumn: _increment_timestamp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pk_company
		dataType: int64
		formatString: 0
		lineageTag: 1a3fbae7-0207-47e9-bf87-234fefdda002
		summarizeBy: none
		sourceColumn: pk_company

		annotation SummarizationSetBy = Automatic

	column CompanyName
		dataType: string
		lineageTag: cf0ac63c-c1f1-4b85-a218-2d2cef9af13f
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column CompanyGroupId
		dataType: string
		lineageTag: 1cdda12a-a338-422d-a998-694bdc413304
		summarizeBy: none
		sourceColumn: CompanyGroupId

		annotation SummarizationSetBy = Automatic

	column CompanyGroupParentId
		dataType: string
		lineageTag: c5b3ec75-b31f-4cc9-9058-face71c9ed91
		summarizeBy: none
		sourceColumn: CompanyGroupParentId

		annotation SummarizationSetBy = Automatic

	column SourceCurrency
		dataType: string
		lineageTag: 5a5c87c1-52c3-4d14-a867-fa94a1bd4b12
		summarizeBy: none
		sourceColumn: SourceCurrency

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a485a2c7-5746-43bf-9780-0eedb144675e
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 797f58a9-7ab3-4f67-90c5-91065de457d9
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 6ae26cbf-0738-4f35-bd94-2cf02f5ad6bb
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column VatNumber
		dataType: string
		lineageTag: 91a1fae7-68cb-4f3a-9c45-2fdd3584b0fa
		summarizeBy: none
		sourceColumn: VatNumber

		annotation SummarizationSetBy = Automatic

	column OrganisationNumber
		dataType: string
		lineageTag: 9329bd2d-9804-437c-a0db-2b7deadf311e
		summarizeBy: none
		sourceColumn: OrganisationNumber

		annotation SummarizationSetBy = Automatic

	partition Company = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-4061987743434543.3.azuredatabricks.net", "/sql/1.0/warehouses/b09a38ac31c647f4", null),
				    prod_gold_Database = Source{[Name="prod_gold",Kind="Database"]}[Data],
				    shareddimensions_Schema = prod_gold_Database{[Name="shareddimensions",Kind="Schema"]}[Data],
				    company_Table = shareddimensions_Schema{[Name="company",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(company_Table,{{"CompanyId", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

