table 'Project Transactions'
	lineageTag: a577b28b-2e28-4c35-97e3-aa68a5a68315

	column Actuality
		dataType: string
		lineageTag: 7fbe90c3-4eff-46ea-93b6-14677003579d
		summarizeBy: none
		sourceColumn: Actuality

		annotation SummarizationSetBy = Automatic

	column ActualityOrigin
		dataType: string
		lineageTag: d3305a4c-1bf3-4a0a-acc7-03dee34b2251
		summarizeBy: none
		sourceColumn: ActualityOrigin

		annotation SummarizationSetBy = Automatic

	column AccountingDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: bfdaf204-fdd4-409a-bd28-50d647e3fe7c
		summarizeBy: none
		sourceColumn: AccountingDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PXPeriodAccounting
		dataType: string
		lineageTag: 6ba40d45-e922-4c1c-ab6c-84f264cea7b4
		summarizeBy: none
		sourceColumn: PXPeriodAccounting

		annotation SummarizationSetBy = Automatic

	column PXPeriodIntended
		dataType: string
		lineageTag: a81a13bc-d7e6-4af3-be5c-8c565653ce34
		summarizeBy: none
		sourceColumn: PXPeriodIntended

		annotation SummarizationSetBy = Automatic

	column IntendedDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f6a28cac-a391-439f-a2eb-b438d6e7f9ec
		summarizeBy: none
		sourceColumn: IntendedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TotalHours
		dataType: double
		lineageTag: 2de8335e-4632-4a0b-a9e4-78f37284b904
		summarizeBy: sum
		sourceColumn: TotalHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NormalWorkingHoursMonthly
		dataType: double
		lineageTag: 30460586-39ee-4523-8e1b-23f9ebe4d67d
		summarizeBy: sum
		sourceColumn: NormalWorkingHoursMonthly

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OverTime
		dataType: double
		lineageTag: 51e6fe40-48a8-43a9-b2c9-eb8af576c750
		summarizeBy: sum
		sourceColumn: OverTime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NoChargeableHour
		dataType: double
		lineageTag: cb26236e-e76a-4014-8668-87db0ce22b8d
		summarizeBy: sum
		sourceColumn: NoChargeableHour

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SourceCurrency
		dataType: string
		lineageTag: d5cffd01-ed9c-479f-b44f-fab43e091138
		summarizeBy: none
		sourceColumn: SourceCurrency

		annotation SummarizationSetBy = Automatic

	column EmployeeUnitId
		dataType: string
		lineageTag: 0037ee92-ea0c-42e7-bf0b-3308d93ba65b
		summarizeBy: none
		sourceColumn: EmployeeUnitId

		annotation SummarizationSetBy = Automatic

	column CompanyEmployeeProjectId
		dataType: string
		lineageTag: 59cad543-0ad8-4dea-8470-496a54fb897a
		summarizeBy: none
		sourceColumn: CompanyEmployeeProjectId

		annotation SummarizationSetBy = Automatic

	column EmployeeFunctionId
		dataType: string
		lineageTag: 4ba399ce-950c-493c-b0f4-96457e771cf8
		summarizeBy: none
		sourceColumn: EmployeeFunctionId

		annotation SummarizationSetBy = Automatic

	column EmploymentTypeId
		dataType: int64
		formatString: 0
		lineageTag: 3d507b8b-f6ad-4cd0-8da9-115b3da3ff9a
		summarizeBy: none
		sourceColumn: EmploymentTypeId

		annotation SummarizationSetBy = Automatic

	column NonChargableId
		dataType: int64
		formatString: 0
		lineageTag: a3177ae9-4ea8-4aa4-b9a9-9def7facaee9
		summarizeBy: count
		sourceColumn: NonChargableId

		annotation SummarizationSetBy = Automatic

	column TransactionType
		dataType: int64
		formatString: 0
		lineageTag: 1df1e97f-621c-43e9-aa8b-590047a7aeb8
		summarizeBy: sum
		sourceColumn: TransactionType

		annotation SummarizationSetBy = Automatic

	column TimeCode
		dataType: string
		lineageTag: 8b7dd8f9-dbed-43c1-b9e3-c4752e7bb1a3
		summarizeBy: none
		sourceColumn: TimeCode

		annotation SummarizationSetBy = Automatic

	column ProjectClassType
		dataType: int64
		formatString: 0
		lineageTag: a7e19bac-a24e-4390-968d-5cd872146ece
		summarizeBy: none
		sourceColumn: ProjectClassType

		annotation SummarizationSetBy = Automatic

	column ProjectEmployeeId
		dataType: string
		lineageTag: fa835d4a-52d4-43d4-8cc7-005b51473ae4
		summarizeBy: none
		sourceColumn: ProjectEmployeeId

		annotation SummarizationSetBy = Automatic

	column ExpenseCode
		dataType: string
		lineageTag: ca692233-77ee-49ae-8a2e-b4bc49f1f25f
		summarizeBy: none
		sourceColumn: ExpenseCode

		annotation SummarizationSetBy = Automatic

	column FteFc
		dataType: double
		lineageTag: 3885a2a8-5e90-46f1-85e7-6f0cf71e2214
		summarizeBy: sum
		sourceColumn: FteFc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UhrFc
		dataType: double
		lineageTag: aedc588d-9252-4ce5-9ceb-e60d1d2d76d9
		summarizeBy: sum
		sourceColumn: UhrFc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CurrencyId
		dataType: int64
		formatString: 0
		lineageTag: e553069d-d446-42a5-9d5a-ac0aca6cb2a2
		summarizeBy: none
		sourceColumn: CurrencyId

		annotation SummarizationSetBy = Automatic

	column ActualityOrigin_new
		dataType: string
		lineageTag: e469d43f-a1c9-4d0d-a8ce-9aa8bf7d9368
		summarizeBy: none
		sourceColumn: ActualityOrigin_new

		annotation SummarizationSetBy = Automatic

	column Actualitydate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a61eaeaa-8023-4892-a9c6-370ae4cda596
		summarizeBy: none
		sourceColumn: Actualitydate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CompanyId
		dataType: string
		lineageTag: 95e55c53-8ada-426c-bfbb-180fab409821
		summarizeBy: none
		sourceColumn: CompanyId

		annotation SummarizationSetBy = Automatic

	column CompanyProjectId
		dataType: string
		lineageTag: c108047c-443e-43a1-b759-209536bd3b80
		summarizeBy: none
		sourceColumn: CompanyProjectId

		annotation SummarizationSetBy = Automatic

	column CompanyProjectEmpId
		dataType: string
		lineageTag: 94a3a739-3f18-46f6-8dbb-de796fbd28b9
		summarizeBy: none
		sourceColumn: CompanyProjectEmpId

		annotation SummarizationSetBy = Automatic

	column CompanyProjectUnitId
		dataType: string
		lineageTag: 3303c837-ff33-4a0b-bc6b-d870c249bec6
		summarizeBy: none
		sourceColumn: CompanyProjectUnitId

		annotation SummarizationSetBy = Automatic

	column ProjectFunctionId
		dataType: string
		lineageTag: 9f04b242-441e-4aa1-83b5-5d0b580a6a23
		summarizeBy: none
		sourceColumn: ProjectFunctionId

		annotation SummarizationSetBy = Automatic

	column CompanyCustomerId
		dataType: string
		lineageTag: 429e1b80-3f94-4791-9f5c-ab09736f2333
		summarizeBy: none
		sourceColumn: CompanyCustomerId

		annotation SummarizationSetBy = Automatic

	column AdjustedFunction
		dataType: string
		lineageTag: 6ab2c9b7-d597-40ad-b259-78c32e3ebaa1
		summarizeBy: none
		sourceColumn: AdjustedFunction

		annotation SummarizationSetBy = Automatic

	column AdjustedFunction2
		dataType: string
		lineageTag: 27976bc5-5d39-4905-b40a-d392b4d9dbc9
		summarizeBy: none
		sourceColumn: AdjustedFunction2

		annotation SummarizationSetBy = Automatic

	column TotalRevenue
		dataType: double
		lineageTag: df9b05bd-d2c9-4a4a-b9b5-2ee28f322562
		summarizeBy: sum
		sourceColumn: TotalRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalCost
		dataType: double
		lineageTag: 44d508b8-30ea-4ea7-8cb6-32f18b482cdc
		summarizeBy: sum
		sourceColumn: TotalCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Project Transactions' = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Source = Databricks.Catalogs("adb-4061987743434543.3.azuredatabricks.net", "/sql/1.0/warehouses/b09a38ac31c647f4", null),
				    prod_gold_Database = Source{[Name="prod_gold",Kind="Database"]}[Data],
				    financereport_Schema = prod_gold_Database{[Name="financereport",Kind="Schema"]}[Data],
				    projecttransactionslocal_Table = financereport_Schema{[Name="projecttransactions",Kind="Table"]}[Data],
				    #"Added Custom" = Table.AddColumn(projecttransactionslocal_Table, "Function", each if [ProjectFunctionId] = "10" then "Prod" else if [ProjectFunctionId] = "20" then "OH" else null),
				    Custom1 = Table.NestedJoin(#"Added Custom", {"SourceCurrency"}, #"Source Currency", {"SourceCurrency"}, "Source Currency", JoinKind.LeftOuter),
				    #"Expanded Source Currency" = Table.ExpandTableColumn(Custom1, "Source Currency", {"CurrencyId"}, {"CurrencyId"}),
				    #"Added Custom1" = Table.AddColumn(#"Expanded Source Currency", "ActualityOrigin_new", each if [ActualityOrigin] is null then "AC" else [ActualityOrigin]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"ActualityOrigin_new", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
				    #"Replaced Value1" = Table.ReplaceValue(#"Filtered Rows","20","",Replacer.ReplaceText,{"ActualityOrigin_new"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Replaced Value1",null,"20",Replacer.ReplaceValue,{"AdjustedFunction2"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value",{"pk_projecttransactions", "_increment_timestamp", "TransactionTypeSortOrder", "VerificationId", "CommissionId", "JointProjectId", "CounterCompanyEmployeeId", "EmployeeObjectiveId", "AmountSelfCost", "EstRemainingHours", "TransferPricing", "MarkUpPerc", "SalaryCost", "Expenses", "AdjustmentExpenses", "EarnedExpenses", "EarnedFee", "EstEndDate", "InvoiceDate", "ItemId", "TaskId", "CounterCompanyProjectId", "CompanyProjActivityType", "CompanyObjectiveId", "CompanyInvoiceNumber", "CompanySupplierId", "Function", "CreatedDate", "CompanyTimeCode", "LocCurrency", "ExchangeRate", "LocalAmountConsFee", "LocExpenseInclTotal", "LocExpenseExclTotal"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

